#!/usr/bin/env python

import rospy
import roslib
import tf

rospy.init_node('tf_raposang_mocap')
tf = tf.TransformBroadcaster()

rate = rospy.Rate(10)
while not rospy.is_shutdown():
    tf.sendTransform([0,0,0], [0,0,0,1], rospy.Time.now(), "world", "map")
    rate.sleep()
